#!/usr/bin/python3
"""
Unit tests for Base class
"""


import unittest
from models import storage
# import pep8
import pycodestyle
import models
from models.base_model import BaseModel
from models.engine import file_storage
from models.amenity import Amenity
from models.city import City
from models.review import Review
from models.place import Place
from models.state import State
from models.user import User
from datetime import datetime
import json
import os


class Test_Base(unittest.TestCase):
    """Base class tests"""

    def test_1(self):
        """  Test Dictionary """
        model = BaseModel()
        model.save()
        new_object = storage.all()
        self.assertEqual(dict, type(new_object))

    def test_pep8(self):
        """Test PEP8."""
        pep8style = pycodestyle.StyleGuide(quiet=True)
        result = pep8style.check_files(['models/engine/file_storage.py'])
        self.assertEqual(result.total_errors, 0,
                         "Found code style errors (and warnings).")


class Test_docstrings_filestorage(unittest.TestCase)


if __name__ == '__main__':
    unittest.main()
